name: Changelog

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for main branch
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ github.token }}
          message: 'chore: update changelog'
          content: |
            ## [{{version}}] - {{date}}
            {{#each changes}}
            ### {{this.type}}
            {{#each this.items}}
            - {{this}}
            {{/each}}
            {{/each}}
      - name: Commit files
        env:
          CI_USER: ${{ secrets.username }}
          CI_EMAIL: ${{ secrets.email }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

      - name: Push changes
        if: env.push == 'true'
        env:
          CI_USER: ${{ secrets.username }}
          CI_TOKEN: ${{ github.token }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:main
